apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-node-exporter
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      relabelConfigs:
        - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
          action: replace
          targetLabel: instance
