apiVersion: v2
name: grafana
version: 1.0.0
Appversion: 1.0.0
description: This Chart deploys grafana.
dependencies:
  - name: grafana
    version: 8.5.3
    repository: https://grafana.github.io/helm-charts
