apiVersion: v2
name: prometheus-operator-crds
version: 1.0.0
description: This Chart deploys prometheus-operator-crds.
dependencies:
  - name: prometheus-operator-crds
    version: 11.0.0
    repository: https://prometheus-community.github.io/helm-charts
